import 'dotenv/config';
import cors from 'cors';
import express from 'express';
import mongoose from 'mongoose';
import swaggerUi from 'swagger-ui-express';
import { z } from 'zod';
import { Action, AiRun, Connection, Creator, Idea, ImportBatch, KnowledgeEntry, Quote, Review, Source, TranscriptChunk, focusAreas, sourceTypes } from './models/Knowledge.js';
import { openapi } from './docs/openapi.js';
import { bulkKnowledgeImportSchema } from './schemas/import.js';
import { importKnowledge, recordImportBatch } from './services/bulkImport.js';
import { hydrateYoutubeSource, processSource } from './services/ingestion.js';

const app = express();
app.use(cors()); app.use(express.json({ limit: '5mb' }));
const id = z.string().regex(/^[a-f\d]{24}$/i, 'Invalid id');
const date = z.string().datetime().optional().or(z.literal(''));
const flexibleFocusArea = z.string().trim().min(1).max(160);
const flexibleReminderFrequency = z.string().trim().min(1).max(80);
const sourceInput = z.object({ type: z.enum(sourceTypes), url: z.string().url().optional().or(z.literal('')), title: z.string().min(1).max(300).optional(), creatorName: z.string().max(200).optional(), publisher: z.string().max(200).optional(), language: z.string().max(20).optional(), rawText: z.string().max(500000).optional(), focusArea: flexibleFocusArea.optional() });
const entryInput = z.object({ title: z.string().min(1).optional(), focusArea: flexibleFocusArea.optional(), centralThesis: z.string().optional(), summary: z.string().optional(), whyItMattersToMe: z.string().optional(), tags: z.array(z.string()).optional(), status: z.enum(['inbox', 'distilled', 'applied', 'archived']).optional(), nextReviewAt: date });
const actionInput = z.object({ text: z.string().min(1), status: z.enum(['open', 'completed', 'dismissed']).optional(), dueAt: date, reminderFrequency: flexibleReminderFrequency.optional() });
const creatorInput = z.object({ name: z.string().min(1), type: z.enum(['person', 'channel', 'publication']).optional(), websiteUrl: z.string().url().optional().or(z.literal('')), youtubeChannelUrl: z.string().url().optional().or(z.literal('')), bio: z.string().optional(), focusAreas: z.array(flexibleFocusArea).optional(), defaultTags: z.array(z.string()).optional() });
const connectionInput = z.object({ fromType: z.enum(['source', 'entry', 'idea']), fromId: id, toType: z.enum(['source', 'entry', 'idea']), toId: id, relationship: z.enum(['supports', 'contradicts', 'extends', 'applies_to', 'related_to']).optional(), note: z.string().optional(), confidence: z.number().min(0).max(1).optional() });
const safe = (data: Record<string, unknown>) => Object.fromEntries(Object.entries(data).filter(([, value]) => value !== '' && value !== undefined));
const asyncRoute = (route: (req: express.Request, res: express.Response) => Promise<unknown>) => (req: express.Request, res: express.Response, next: express.NextFunction) => route(req, res).catch(next);

app.get('/health', (_req, res) => res.json({ ok: true, ai: { provider: 'ollama', configured: Boolean(process.env.OLLAMA_BASE_URL || true), model: process.env.OLLAMA_MODEL || 'qwen2.5:7b' } }));
app.get('/api/config', (_req, res) => res.json({ providers: [{ id: 'ollama', configured: true, model: process.env.OLLAMA_MODEL || 'qwen2.5:7b', baseUrl: process.env.OLLAMA_BASE_URL || 'http://host.docker.internal:11434' }, { id: 'gemini', configured: Boolean(process.env.GEMINI_API_KEY) }, { id: 'groq', configured: Boolean(process.env.GROQ_API_KEY) }] }));
app.get('/api/areas', (_req, res) => res.json(focusAreas));
app.get('/api/docs/openapi.json', (_req, res) => res.json(openapi));
app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(openapi, { customSiteTitle: 'Knowledge Hub API Docs' }));

app.post('/api/v1/imports/knowledge', asyncRoute(async (req, res) => {
  const payload = bulkKnowledgeImportSchema.parse(req.body); const results: { sourceId?: string; entryId?: string; lessons?: number; quotes?: number; actions?: number; error?: string }[] = [];
  for (const item of payload.imports) {
    try { results.push(await importKnowledge(item)); }
    catch (error) { results.push({ error: error instanceof Error ? error.message : 'Import failed' }); if (!payload.continueOnError) break; }
  }
  const batch = await recordImportBatch(payload.imports.length, results, payload.imports[0]?.origin);
  res.status(batch.failed ? 207 : 201).json({ batchId: batch._id, status: batch.status, requested: batch.requested, created: batch.created, failed: batch.failed, results });
}));
app.get('/api/v1/imports', asyncRoute(async (_req, res) => res.json(await ImportBatch.find().sort({ createdAt: -1 }).limit(50).lean())));

app.get('/api/sources', asyncRoute(async (req, res) => { const filter: Record<string, unknown> = {}; if (req.query.status) filter.status = req.query.status; if (req.query.type) filter.type = req.query.type; if (req.query.search) filter.$text = { $search: String(req.query.search) }; res.json(await Source.find(filter).sort({ updatedAt: -1 }).lean()); }));
app.post('/api/sources', asyncRoute(async (req, res) => { const data = safe(sourceInput.parse(req.body)); const source = await Source.create({ ...data, title: data.title || 'Untitled source' }); if (source.type === 'youtube' && source.url) await hydrateYoutubeSource(String(source._id)); res.status(201).json(await Source.findById(source._id)); }));
app.get('/api/sources/:id', asyncRoute(async (req, res) => { const sourceId = id.parse(req.params.id); const source = await Source.findById(sourceId).lean(); if (!source) return res.status(404).json({ message: 'Source not found' }); const [entry, chunks, runs] = await Promise.all([KnowledgeEntry.findOne({ sourceId }).lean(), TranscriptChunk.find({ sourceId }).sort({ position: 1 }).lean(), AiRun.find({ sourceId }).sort({ createdAt: -1 }).lean()]); const [ideas, quotes, actions] = entry ? await Promise.all([Idea.find({ knowledgeEntryId: entry._id }).lean(), Quote.find({ knowledgeEntryId: entry._id }).lean(), Action.find({ knowledgeEntryId: entry._id }).lean()]) : [[], [], []]; res.json({ source, entry, chunks, ideas, quotes, actions, runs }); }));
app.patch('/api/sources/:id', asyncRoute(async (req, res) => { const sourceId = id.parse(req.params.id); const source = await Source.findByIdAndUpdate(sourceId, safe(sourceInput.partial().parse(req.body)), { new: true, runValidators: true }); if (!source) return res.status(404).json({ message: 'Source not found' }); res.json(source); }));
app.post('/api/sources/:id/process', asyncRoute(async (req, res) => { const sourceId = id.parse(req.params.id); const source = await Source.findById(sourceId); if (!source) return res.status(404).json({ message: 'Source not found' }); source.status = 'queued'; source.failureReason = undefined; await source.save(); void processSource(sourceId); res.status(202).json({ message: 'AI distillation queued', sourceId }); }));
app.post('/api/sources/:id/approve', asyncRoute(async (req, res) => { const sourceId = id.parse(req.params.id); const [source, entry] = await Promise.all([Source.findById(sourceId), KnowledgeEntry.findOne({ sourceId })]); if (!source || !entry) return res.status(404).json({ message: 'A processed source is required before approval' }); const now = new Date(); source.status = 'approved'; entry.status = 'distilled'; entry.approvedAt = now; entry.nextReviewAt = new Date(now.getTime() + 7 * 86400000); await Promise.all([source.save(), entry.save(), Idea.updateMany({ knowledgeEntryId: entry._id }, { approved: true }), Quote.updateMany({ knowledgeEntryId: entry._id }, { approved: true })]); res.json({ source, entry }); }));
app.post('/api/sources/:id/reject', asyncRoute(async (req, res) => { const source = await Source.findByIdAndUpdate(id.parse(req.params.id), { status: 'rejected' }, { new: true }); if (!source) return res.status(404).json({ message: 'Source not found' }); res.json(source); }));
app.delete('/api/sources/:id', asyncRoute(async (req, res) => { const sourceId = id.parse(req.params.id); const entry = await KnowledgeEntry.findOne({ sourceId }); await Promise.all([Source.findByIdAndDelete(sourceId), TranscriptChunk.deleteMany({ sourceId }), AiRun.deleteMany({ sourceId }), Quote.deleteMany({ sourceId }), entry ? Idea.deleteMany({ knowledgeEntryId: entry._id }) : Promise.resolve(), entry ? Action.deleteMany({ knowledgeEntryId: entry._id }) : Promise.resolve(), KnowledgeEntry.deleteOne({ sourceId })]); res.status(204).end(); }));

app.get('/api/knowledge', asyncRoute(async (req, res) => { const filter: Record<string, unknown> = {}; if (req.query.area) filter.focusArea = req.query.area; if (req.query.status) filter.status = req.query.status; if (req.query.search) filter.$text = { $search: String(req.query.search) }; const entries = await KnowledgeEntry.find(filter).sort({ updatedAt: -1 }).lean(); const results = await Promise.all(entries.map(async entry => ({ ...entry, source: await Source.findById(entry.sourceId).lean(), ideas: await Idea.find({ knowledgeEntryId: entry._id }).lean(), actions: await Action.find({ knowledgeEntryId: entry._id }).lean() }))); res.json(results); }));
app.get('/api/knowledge/:id', asyncRoute(async (req, res) => { const entry = await KnowledgeEntry.findById(id.parse(req.params.id)).lean(); if (!entry) return res.status(404).json({ message: 'Knowledge entry not found' }); const [source, ideas, quotes, actions, reviews, connections] = await Promise.all([Source.findById(entry.sourceId).lean(), Idea.find({ knowledgeEntryId: entry._id }).lean(), Quote.find({ knowledgeEntryId: entry._id }).lean(), Action.find({ knowledgeEntryId: entry._id }).lean(), Review.find({ knowledgeEntryId: entry._id }).sort({ reviewedAt: -1 }).lean(), Connection.find({ $or: [{ fromId: entry._id }, { toId: entry._id }] }).lean()]); res.json({ entry, source, ideas, quotes, actions, reviews, connections }); }));
app.patch('/api/knowledge/:id', asyncRoute(async (req, res) => { const entry = await KnowledgeEntry.findByIdAndUpdate(id.parse(req.params.id), safe(entryInput.parse(req.body)), { new: true, runValidators: true }); if (!entry) return res.status(404).json({ message: 'Knowledge entry not found' }); res.json(entry); }));
app.post('/api/knowledge/:id/reviews', asyncRoute(async (req, res) => { const entryId = id.parse(req.params.id); const data = z.object({ reflection: z.string().optional(), didIApplyIt: z.boolean().optional(), outcome: z.string().optional(), nextReviewAt: date }).parse(req.body); const review = await Review.create({ knowledgeEntryId: entryId, ...safe(data) }); await KnowledgeEntry.findByIdAndUpdate(entryId, { lastReviewedAt: new Date(), nextReviewAt: data.nextReviewAt || new Date(Date.now() + 30 * 86400000) }); res.status(201).json(review); }));
app.post('/api/knowledge/:id/actions', asyncRoute(async (req, res) => { const action = await Action.create({ knowledgeEntryId: id.parse(req.params.id), ...safe(actionInput.parse(req.body)) }); res.status(201).json(action); }));
app.patch('/api/actions/:id', asyncRoute(async (req, res) => { const data = actionInput.partial().parse(req.body); const action = await Action.findByIdAndUpdate(id.parse(req.params.id), { ...safe(data), ...(data.status === 'completed' ? { completedAt: new Date() } : {}) }, { new: true }); if (!action) return res.status(404).json({ message: 'Action not found' }); res.json(action); }));
app.patch('/api/ideas/:id', asyncRoute(async (req, res) => { const data = z.object({ title: z.string().min(1).optional(), explanation: z.string().optional(), approved: z.boolean().optional() }).parse(req.body); const idea = await Idea.findByIdAndUpdate(id.parse(req.params.id), data, { new: true, runValidators: true }); if (!idea) return res.status(404).json({ message: 'Idea not found' }); res.json(idea); }));
app.patch('/api/quotes/:id', asyncRoute(async (req, res) => { const data = z.object({ text: z.string().min(1).optional(), approved: z.boolean().optional() }).parse(req.body); const quote = await Quote.findByIdAndUpdate(id.parse(req.params.id), data, { new: true, runValidators: true }); if (!quote) return res.status(404).json({ message: 'Quote not found' }); res.json(quote); }));

app.get('/api/reminders', asyncRoute(async (_req, res) => { const now = new Date(); const [actions, reviews] = await Promise.all([Action.find({ status: 'open', $or: [{ dueAt: { $lte: now } }, { dueAt: null }] }).sort({ dueAt: 1 }).limit(10).lean(), KnowledgeEntry.find({ status: { $in: ['distilled', 'applied'] }, nextReviewAt: { $lte: now } }).sort({ nextReviewAt: 1 }).limit(5).lean()]); res.json({ actions, reviews }); }));
app.get('/api/dashboard', asyncRoute(async (_req, res) => { const [total, distilled, applied, inbox, areas, recent, due] = await Promise.all([KnowledgeEntry.countDocuments(), KnowledgeEntry.countDocuments({ status: 'distilled' }), KnowledgeEntry.countDocuments({ status: 'applied' }), Source.countDocuments({ status: { $in: ['draft', 'queued', 'processing', 'ready_for_review'] } }), KnowledgeEntry.aggregate([{ $group: { _id: '$focusArea', count: { $sum: 1 } } }]), KnowledgeEntry.find().sort({ updatedAt: -1 }).limit(6).lean(), Action.countDocuments({ status: 'open', dueAt: { $lte: new Date() } })]); res.json({ total, distilled, applied, inbox, due, areas, recent }); }));
app.get('/api/creators', asyncRoute(async (_req, res) => res.json(await Creator.find().sort({ name: 1 }).lean())));
app.post('/api/creators', asyncRoute(async (req, res) => res.status(201).json(await Creator.create(safe(creatorInput.parse(req.body))))));
app.patch('/api/creators/:id', asyncRoute(async (req, res) => { const creator = await Creator.findByIdAndUpdate(id.parse(req.params.id), safe(creatorInput.partial().parse(req.body)), { new: true, runValidators: true }); if (!creator) return res.status(404).json({ message: 'Creator not found' }); res.json(creator); }));
app.delete('/api/creators/:id', asyncRoute(async (req, res) => { const creator = await Creator.findByIdAndDelete(id.parse(req.params.id)); if (!creator) return res.status(404).json({ message: 'Creator not found' }); res.status(204).end(); }));
app.get('/api/connections', asyncRoute(async (req, res) => { const filter: Record<string, unknown> = {}; if (req.query.id) filter.$or = [{ fromId: id.parse(String(req.query.id)) }, { toId: id.parse(String(req.query.id)) }]; res.json(await Connection.find(filter).sort({ updatedAt: -1 }).lean()); }));
app.post('/api/connections', asyncRoute(async (req, res) => res.status(201).json(await Connection.create(connectionInput.parse(req.body)))));
app.patch('/api/connections/:id', asyncRoute(async (req, res) => { const connection = await Connection.findByIdAndUpdate(id.parse(req.params.id), connectionInput.partial().parse(req.body), { new: true, runValidators: true }); if (!connection) return res.status(404).json({ message: 'Connection not found' }); res.json(connection); }));
app.delete('/api/connections/:id', asyncRoute(async (req, res) => { const connection = await Connection.findByIdAndDelete(id.parse(req.params.id)); if (!connection) return res.status(404).json({ message: 'Connection not found' }); res.status(204).end(); }));

app.use((error: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => { if (error instanceof z.ZodError) return res.status(400).json({ message: 'Validation failed', issues: error.flatten() }); if (error instanceof mongoose.Error.CastError) return res.status(400).json({ message: 'Invalid document id' }); console.error(error); res.status(500).json({ message: error instanceof Error ? error.message : 'Server error' }); });
const port = Number(process.env.PORT || 4000);
mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/knowledge-hub').then(() => app.listen(port, () => console.log(`Knowledge Hub API on :${port}`))).catch(console.error);
